# Generated by Django 2.2.10 on 2020-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('П', 'Полик'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
